### ISSUE TITLE
Conflict with calibre's "ebook-viewer"

### ISSUE THREAD

**Issue by dyskette** [michaldaniel/Ebook-Viewer#1]
The binary actually replaces or gets replaced by calibre's ebook-viewer. This would create a conflict if you want it packaged for any distribution.

**Comment by michaldaniel** [comment]
Thanks for letting me know, I'll get it sorted out on weekend.

**Comment by michaldaniel** [comment]
I decided to rename it to "Easy eBook Viewr", we also got new icon, gotta update readme. This weekend took a while.
