### ISSUE TITLE
Error opening book without author name metadata

### ISSUE THREAD

**Issue by pebmp17** [michaldaniel/Ebook-Viewer#15]
Hi, sorry for bothering you with another issue. This time, by taking a quick look at traceback, seems to be related with the book not having the authors name. When trying to open this book from the file manager the program window doesn't appear, and when trying to open using the "Please choose a file" dialog nothing from the book would show up. In the terminal I got this error:

`Traceback (most recent call last):
  File "/usr/share/easy-ebook-viewer/components/header_bar.py", line 229, in __on_open_clicked
    self.__window.load_book_data(filename)
  File "/usr/share/easy-ebook-viewer/main_window.py", line 331, in load_book_data
    self.__continiue_book_loading(filename)
  File "/usr/share/easy-ebook-viewer/main_window.py", line 279, in __continiue_book_loading
    if self.content_provider.prepare_book(filename):
  File "/usr/share/easy-ebook-viewer/workers/content_provider.py", line 89, in prepare_book
    self.book_name = str(bytes.decode(str(metadata.metadata.dc_title).encode("utf-8")))
AttributeError: 'NoneType' object has no attribute 'dc_title'
`

If you want, I can send the ebook for you have a better look at it.

**Comment by michaldaniel** [comment]
Please bother me with as many issue as you can. Can you send me a book to my email (if it can be shared publicly) contact@michaldaniel.work

**Comment by pebmp17** [comment]
Sure, the book is even in public domain, I guess. You should expect to receive a email with the same title as this issue from pedrobmp3@gmail.com.

**Comment by michaldaniel** [comment]
Should be all dandy now. Thanks for help.

**Comment by pebmp17** [comment]
No problem, thank you.
