### ISSUE TITLE
"Importing is unavailable" message can't be dismissed

### ISSUE THREAD

**Issue by TimoWilken** [michaldaniel/Ebook-Viewer#18]
When clicking the "Import book" menu item, an error message pops up ("Importing is unavailable - Importing requires Calibre eBook reader to be installed."). This dialog window can't be dismissed - when I click "OK", the main window is not dimmed any more, but the dialog stays open.

**System information**: Arch Linux, installed ebook-viewer package a few minutes ago using the PKGBUILD from #10. `gtk3` package version 3.22.4-1.

**Comment by Keepco** [comment]
Can reproduce, the dialog window can't be dismissed

**Comment by michaldaniel** [comment]
Thanks for noticing me.
