### ISSUE TITLE
Index with chapters

### ISSUE THREAD

**Issue by fturco** [michaldaniel/Ebook-Viewer#2]
It would be cool to be able to show the index of a book (list of chapters).

**Comment by michaldaniel** [comment]
This is all planned as part of pPub re-write. I should make it clear for now as part of readme, thanks for taking notice.

**Comment by fturco** [comment]
Is this project related to pPub? I didn't know that.

**Comment by michaldaniel** [comment]
It is. While it can hardly be called fork it is closely related. I'm doing one-by-one re-write of it as I found old pPub too hard to work with.

**Comment by michaldaniel** [comment]
I updated the reamed accordingly for now. I'll have more time to sit on this in two or three days.

**Comment by michaldaniel** [comment]
That should do? I'll add ability to hide and show it soon, but index is available as of now.

**Comment by fturco** [comment]
Great job!
