### ISSUE TITLE
dependency required on ubuntu 17.04

### ISSUE THREAD

**Issue by solinium** [michaldaniel/Ebook-Viewer#33]
On Ubuntu 17.04, gir1.2-webkit-3.0 is required install before it runs. It should probably be added to the readme.

**Comment by Keepco** [comment]
The way I read the README it already states that, see the following sentence under **Installing**

> Requires: gir1.2-webkit-3.0, libwebkitgtk-3.0-0, gir1.2-gtk-3.0, python3-gi (PyGObject for Python 3)

**Comment by solinium** [comment]
@Keepco I apologize, I didn't see that. Sorry for the inconvenience.
