### ISSUE TITLE
Just wanted to say thank you

### ISSUE THREAD

**Issue by uuencode** [michaldaniel/Ebook-Viewer#5]
I just wanted to say thank you but there was no other option to do so. That was one thing I missed from Windows - a decent epub reader, the other VirtualDub. The app is great and I wish I could set it as a default app to open epub, however, it doesn't work - the app opens when I double click an epub file in Nautilus but the file is not loaded. Anyway, thank you and keep up the good work!

**Comment by michaldaniel** [comment]
That is so sweet.  :heart: 

I'll open separate bug for file opening like that, that needs to work. App is so not ready yet. Please give it two or three more months, it should be really usable by then, I don't have big plans for it but it should do well what it's supposed to do.

**Comment by uuencode** [comment]
Thank you!

**Comment by michaldaniel** [comment]
@uuencode That was rather quick edit turns out. Opening from file explorer works now.
