### ISSUE TITLE
dose it support reading text files in Ebook-Viewer

### ISSUE THREAD

**Issue by csrgxtu** [michaldaniel/Ebook-Viewer#9]
i have some books in text format, and your view page looks beautiful, so i am wondering if it can read text files.

**Comment by michaldaniel** [comment]
Not yet but I'm going to use standalone caliber tool 'ebook-convert' that allows me to convert a lot of other formats into epub, incluging TXT files. So in general they should work too as far as the converter works but converting waits for when all other stuff for 1.0 is cleared as sort of "cherry on top" when I know other epub stuff works fine.

**Comment by michaldaniel** [comment]
It sort of does now. I plan to include txt, non-drm mobi, html native support since I just learned that `ebook-convert` is inseparable from Calibre and can't be used and installed as standalone tool. But since importing works now I'm going to close it for 1.0 milestone.
